/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario.view;

import sistemabancario.controller.ClienteController;

/**
 *
 * @author Franshinsca
 */
public class BotoesClienteView extends javax.swing.JPanel {

    /**
     * Creates new form BotoesClienteView
     */
    public BotoesClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNovoCliente = new javax.swing.JButton();
        bListarClientes = new javax.swing.JButton();
        bOrdenarClientes = new javax.swing.JButton();
        bAlterarCliente = new javax.swing.JButton();
        bExcluirCliente = new javax.swing.JButton();

        bNovoCliente.setText("Novo Cliente");

        bListarClientes.setText("Listar Clientes");

        bOrdenarClientes.setText("Ordenar Clientes");

        bAlterarCliente.setText("Atualizar Cliente");

        bExcluirCliente.setText("Excluir Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListarClientes)
                    .addComponent(bNovoCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAlterarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(bExcluirCliente))
                    .addComponent(bOrdenarClientes))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bListarClientes)
                    .addComponent(bOrdenarClientes))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNovoCliente)
                    .addComponent(bAlterarCliente)
                    .addComponent(bExcluirCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterarCliente;
    private javax.swing.JButton bExcluirCliente;
    private javax.swing.JButton bListarClientes;
    private javax.swing.JButton bNovoCliente;
    private javax.swing.JButton bOrdenarClientes;
    // End of variables declaration//GEN-END:variables

    public void setController(ClienteController controller) {
      
        this.bNovoCliente.addActionListener(e -> controller.criarCliente());
        this.bAlterarCliente.addActionListener(e -> controller.atualizarCliente());
        this.bExcluirCliente.addActionListener(e -> controller.excluirCliente());
        this.bListarClientes.addActionListener(e -> controller.listarClientes());
        this.bOrdenarClientes.addActionListener(e -> controller.ordenarClientes());
    }
}
