package sistemabancario.view;

import javax.swing.JTextField;
import sistemabancario.controller.ClienteController;

public class BotoesClienteView extends javax.swing.JPanel {

    public BotoesClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bNovoCliente = new javax.swing.JButton();
        bListarClientes = new javax.swing.JButton();
        bOrdenarClientes = new javax.swing.JButton();
        bAlterarCliente = new javax.swing.JButton();
        bExcluirCliente = new javax.swing.JButton();
        campoCPF = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        campoListar = new javax.swing.JTextField();
        comboboxLista = new javax.swing.JComboBox<>();
        comboboxOrdenar = new javax.swing.JComboBox<>();

        bNovoCliente.setText("Novo Cliente");

        bListarClientes.setText("Listar Clientes");

        bOrdenarClientes.setText("Ordenar Clientes");

        bAlterarCliente.setText("Atualizar Cliente");

        bExcluirCliente.setText("Excluir Cliente");

        campoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFActionPerformed(evt);
            }
        });

        labelCPF.setText("CPF");

        campoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoListarActionPerformed(evt);
            }
        });

        comboboxLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos os clientes", "Nome (ou parte)", "Sobrenome (ou parte)", "RG", "CPF" }));

        comboboxOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Sobrenome", "Salario" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoListar)
                            .addComponent(bListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboboxLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNovoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCPF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboboxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bExcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAlterarCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bOrdenarClientes)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoListar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOrdenarClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bListarClientes)
                .addGap(18, 18, 18)
                .addComponent(bExcluirCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAlterarCliente)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNovoCliente)
                    .addComponent(labelCPF))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPFActionPerformed

    private void campoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterarCliente;
    private javax.swing.JButton bExcluirCliente;
    private javax.swing.JButton bListarClientes;
    private javax.swing.JButton bNovoCliente;
    private javax.swing.JButton bOrdenarClientes;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoListar;
    private javax.swing.JComboBox<String> comboboxLista;
    private javax.swing.JComboBox<String> comboboxOrdenar;
    private javax.swing.JLabel labelCPF;
    // End of variables declaration//GEN-END:variables

    public void setController(ClienteController controller) {
      
        this.bNovoCliente.addActionListener(e -> controller.inserirCliente());
        this.bAlterarCliente.addActionListener(e -> controller.buscarCliente());
        this.bExcluirCliente.addActionListener(e -> controller.excluirCliente());
        this.bListarClientes.addActionListener(e -> {
            int listar = comboboxLista.getSelectedIndex();
            switch(listar){
                case 0: //listar todos os clientes
                    controller.listarClientes();
                    break;
                case 1: //listar por nome ou parte
                    controller.listarPorNome();
                    break;
                case 2: //listar por sobrenome ou parte
                    controller.listarPorSobrenome();
                    break;
                case 3: //listar por rg
                    controller.listarPorRg();
                    break;
                case 4: //listar por cpf
                    controller.listarPorCpf();
                    break;
            }});
        this.bOrdenarClientes.addActionListener(e -> {
            int ordenar = comboboxOrdenar.getSelectedIndex();
            controller.ordenarClientes(ordenar);
        });
    }
    
    public JTextField getCampoCPF() {
        return campoCPF;
    }
    
    public JTextField getCampoListar() {
        return campoListar;
    }
}
