/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario.view;

import javax.swing.JTextField;
import sistemabancario.controller.ContaController;

/**
 *
 * @author eduar
 */
public class PainelContaCorrente extends javax.swing.JPanel {

    /**
     * Creates new form PainelContaCorrente
     */
    public PainelContaCorrente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDepositoInicial = new javax.swing.JLabel();
        labelLimite = new javax.swing.JLabel();
        labelNumConta = new javax.swing.JLabel();
        campoNumConta = new javax.swing.JTextField();
        campoDepositoInicial = new javax.swing.JTextField();
        campoLimite = new javax.swing.JTextField();
        bCriarConta = new javax.swing.JButton();

        labelDepositoInicial.setText("Depósito Inicial:    R$");

        labelLimite.setText("Limite:                   R$");

        labelNumConta.setText("Número da Conta:");

        campoNumConta.setEditable(false);
        campoNumConta.setText("NÚMERO");

        bCriarConta.setText("Criar Conta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDepositoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addComponent(labelNumConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoDepositoInicial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoLimite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoNumConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCriarConta)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepositoInicial)
                    .addComponent(campoDepositoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLimite)
                    .addComponent(campoLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumConta))
                .addGap(18, 18, 18)
                .addComponent(bCriarConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCriarConta;
    private javax.swing.JTextField campoDepositoInicial;
    private javax.swing.JTextField campoLimite;
    private javax.swing.JTextField campoNumConta;
    private javax.swing.JLabel labelDepositoInicial;
    private javax.swing.JLabel labelLimite;
    private javax.swing.JLabel labelNumConta;
    // End of variables declaration//GEN-END:variables

    void setController(ContaController controller) {
        this.bCriarConta.addActionListener(e -> controller.criarConta(1));
    }

    public JTextField getCampoDepositoInicial() {
        return campoDepositoInicial;
    }

    public JTextField getCampoLimite() {
        return campoLimite;
    }

    public JTextField getCampoNumConta() {
        return campoNumConta;
    }
    
    public void limparFormulario(){
        campoLimite.setText("");
        campoDepositoInicial.setText("");
    }
    
}
