/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario.view;

/**
 *
 * @author eduar
 */
public class PainelContaCliente extends javax.swing.JPanel {

    /**
     * Creates new form PainelContaCliente
     */
    public PainelContaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOperacao = new javax.swing.JLabel();
        bConfirmar = new javax.swing.JButton();
        campoValor = new javax.swing.JTextField();
        labelOperacao2 = new javax.swing.JLabel();

        labelOperacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelOperacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bConfirmar.setText("Confirmar");

        labelOperacao2.setText("Valor:  R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bConfirmar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addComponent(labelOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelOperacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOperacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(bConfirmar))
        );
    }// </editor-fold>//GEN-END:initComponents
    
   public void setLabels(int i){
        switch(i){
            case 0:{
                labelOperacao.setText("SAQUE");
                campoValor.setEditable(true);
                bConfirmar.setVisible(true);
                break;
            }
            case 1:{
                labelOperacao.setText("DEPÓSITO");
                campoValor.setEditable(true);
                bConfirmar.setVisible(true);
                break;
            }
            case 2:{
                labelOperacao.setText("SALDO");
                campoValor.setEditable(false);
                bConfirmar.setVisible(false);
                break;
            }
            case 3:{
                labelOperacao.setText("REMUNERA");
                campoValor.setEditable(true);
                bConfirmar.setVisible(true);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirmar;
    private javax.swing.JTextField campoValor;
    private javax.swing.JLabel labelOperacao;
    private javax.swing.JLabel labelOperacao2;
    // End of variables declaration//GEN-END:variables
}
