/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario.view;

import javax.swing.JTextField;
import sistemabancario.controller.ContaController;

/**
 *
 * @author eduar
 */
public class PainelContaInvestimento extends javax.swing.JPanel {

    /**
     * Creates new form PainelContaInvestimento
     */
    public PainelContaInvestimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMontanteMinimo = new javax.swing.JLabel();
        labelDepositoMinimo = new javax.swing.JLabel();
        labelDepositoInicial = new javax.swing.JLabel();
        campoMontanteMinimo = new javax.swing.JTextField();
        campoDepositoMinimo = new javax.swing.JTextField();
        campoDepositoInicial = new javax.swing.JTextField();
        bCriarConta = new javax.swing.JButton();

        labelMontanteMinimo.setText("Montante Mínimo:  R$");

        labelDepositoMinimo.setText("Depósito Mínimo:   R$");

        labelDepositoInicial.setText("Depósito Inicial:    R$");

        bCriarConta.setText("Criar Conta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMontanteMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoMontanteMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDepositoInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoDepositoInicial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDepositoMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoDepositoMinimo)))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCriarConta)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMontanteMinimo)
                    .addComponent(campoMontanteMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepositoMinimo)
                    .addComponent(campoDepositoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepositoInicial)
                    .addComponent(campoDepositoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCriarConta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCriarConta;
    private javax.swing.JTextField campoDepositoInicial;
    private javax.swing.JTextField campoDepositoMinimo;
    private javax.swing.JTextField campoMontanteMinimo;
    private javax.swing.JLabel labelDepositoInicial;
    private javax.swing.JLabel labelDepositoMinimo;
    private javax.swing.JLabel labelMontanteMinimo;
    // End of variables declaration//GEN-END:variables
    
    //seta botão e sua ação
    void setController(ContaController controller) {
        this.bCriarConta.addActionListener(e -> controller.criarConta(2));
    }

    public JTextField getCampoDepositoInicial() {
        return campoDepositoInicial;
    }

    public JTextField getCampoDepositoMinimo() {
        return campoDepositoMinimo;
    }

    public JTextField getCampoMontanteMinimo() {
        return campoMontanteMinimo;
    }
    
    //limpa formulário de criação de conta
    public void limparFormulario(){
        campoDepositoInicial.setText("");
        campoDepositoMinimo.setText("");
        campoMontanteMinimo.setText("");
    }
    
}
